language: go
go:
  - 1.1.2
  - 1.2
  - tip
env:
  - GOARCH=amd64
  - GOARCH=386
install:
  - sudo git clone https://git.fedorahosted.org/git/lvm2.git /usr/local/lvm2
  - pushd /usr/local/lvm2
  - sudo git checkout v2_02_103
  - sudo ./configure --enable-static_link
  - sudo make device-mapper
  - sudo make install_device-mapper
  - popd
  - go get -d ./...
  - go get github.com/kr/godep
script:
  - export PATH="$HOME/gopath/bin:$PATH"
  - godep restore ./...
  - godep go test ./...
